### ISSUE TITLE
job is failed: Error: NameError: name 'kmeans' is not defined

### ISSUE THREAD

**Issue by HermannLizard** [imgcook/pipcook-plugin-pytorch-yolov5-model-train#2]
运行pipcook主页的例子《识别图片中的前端组件》时报错：
job is failed: Error: NameError: name 'kmeans' is not defined
At:
  ./node_modules/@pipcook/plugins-pytorch-yolov5-model-train/tools/general.py(100): kmean_anchors
  ./node_modules/@pipcook/plugins-pytorch-yolov5-model-train/tools/general.py(623): check_anchors
  ./node_modules/@pipcook/plugins-pytorch-yolov5-model-train/__init__.py(141): train
  ./node_modules/@pipcook/plugins-pytorch-yolov5-model-train/__init__.py(289): main

    at Function.value (/Users/hermannlizard/.pipcook/server/node_modules/@pipcook/boa/lib/index.js:204:25)
    at Object.apply (/Users/hermannlizard/.pipcook/server/node_modules/@pipcook/boa/lib/index.js:401:26)
    at /Users/hermannlizard/.pipcook/server/node_modules/@pipcook/costa/dist/src/client/loaders/python.js:8:24
    at /Users/hermannlizard/.pipcook/server/node_modules/@pipcook/costa/dist/src/client/entry.js:142:32
    at Generator.next (<anonymous>)
    at /Users/hermannlizard/.pipcook/server/node_modules/@pipcook/costa/dist/src/client/entry.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/hermannlizard/.pipcook/server/node_modules/@pipcook/costa/dist/src/client/entry.js:23:12)
    at emitStart (/Users/hermannlizard/.pipcook/server/node_modules/@pipcook/costa/dist/src/client/entry.js:85:12)
    at /Users/hermannlizard/.pipcook/server/node_modules/@pipcook/costa/dist/src/client/entry.js:202:13

后面还有：
job is failed: Error: NameError: name 'tqdm' is not defined
job is failed: TypeError: ModuleNotFoundError: No module named 'PIL'

**Comment by yorkie** [comment]
@HermannLizard @rickycao-qy could this be closed?

**Comment by HermannLizard** [comment]
> @HermannLizard @rickycao-qy could this be closed?

OK. Everything is running for me now. Thx!
However, model train process is verrrrrrrry slow... 
`
 Starting training for 300 epochs...
⚠ run pipeline from pipeline dm6w7alu
⚠      Epoch   gpu_mem       box       obj       cls     total   targets  img_size
⚠ Epoch: 0

⚠      0/299        0G   0.07528    0.0932   0.01748     0.186       192       640
⚠ Current Best Map: [0.04981411]
⚠ Epoch: 1
`
Epoch: 0 took about 2h on my pc, and I have another 299 epochs coming…

My mac info:
MacBook Pro (16-inch, 2019)
2.6 GHz 六核Intel Core i7
16 GB 2667 MHz DDR4
AMD Radeon Pro 5300M 4 GB
Intel UHD Graphics 630 1536 MB

Is that normal for this PC taking this long to run trainings? Or did I have something wrong in my configuration, any suggestions? Thanks a lot

**Comment by FeelyChau** [comment]
@HermannLizard  Generally speaking, using NVIDIA's GPU can speed up the training, but each epoch takes 2 hours, which is abnormal.
